### ISSUE TITLE
Readme Getting Started - Fails to run when following local setup instructions

### ISSUE THREAD

**Issue by jwheeler-creates** [i-am-bee/bee-ui#34]
## Description 
When running locally per readme instructions, the ui fails to load as expected. 

## To Reproduce
1. Download from github repo
2. unzip and cd into the directory
3. run `nvm install && nvm use`
3. run `pnpm install`
4. run `pnpm start:dev`
5. Open [http://localhost:3000](http://localhost:3000) with local browser.

Output:

service_unavailable
The API server is probably unavailable.

Console output:
``` console
  ▲ Next.js 14.2.10
  - Local:        http://localhost:3000
  - Environments: .env
  - Experiments (use with caution):
    · instrumentationHook

 ✓ Starting...
 ○ Compiling /instrumentation ...
 ✓ Compiled /instrumentation in 716ms (718 modules)
 ✓ Ready in 2.1s
 ✓ Compiled /src/middleware in 139ms (359 modules)
 ○ Compiling / ...
 ✓ Compiled / in 5.2s (2941 modules)
 GET / 307 in 5496ms
 ○ Compiling /[projectId] ...
 ✓ Compiled /[projectId] in 4.9s (5348 modules)
TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at afterConnectMultiple (node:net:1667:5)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
 GET /proj_670cc04869ddffe24f4fd70f 200 in 12344ms
```

## Expected behavior
The UI should load as expected and be able to interact with the bee agent framework.

## Desktop (please complete the following information):
- OS: MacOS
- Browser Chrome

## Additional context

nvm which
~/.nvm/versions/node/v20.11.1/bin/node

pnpm version
{
  'bee-ui': '0.0.1',
  npm: '10.2.4',
  node: '20.11.1',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.20.1',
  base64: '0.5.1',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.58.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.13+quic',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.28.3',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '11.3.244.8-node.17',
  zlib: '1.2.13.1-motley-5daffc7'
}

**Comment by jwheeler-liveops** [comment]
This is addressed on this pull request, tested and confirmed. 

#35
