### ISSUE TITLE
Shell and Global Nav Improvements

### ISSUE THREAD

**Issue by geneknit** [i-am-bee/bee-ui#68]
Target release: Iteration 16 (Dec 6)

Status: `blocked` Pending new IA/UX treatment from decision to treat apps as artifacts

## Description
Improvements to the global nav and shell to 
- simplify user interaction with nav
- make it easy to navigate from using one bee to a library of bees
- make user settings more accesible and visible
- de-emphisize "recent bees" in favor of access to tools and knowledge within a workspace

## Motivation
Users today have difficulty
- understanding they can pin the left nav (and therefore accessing navigation)
- navigating back to their library of bees when they are in a specific bee

## Proposed solution
- permanent top nav bar
- lefthand toolbar accessible from traditional hamburger menu
- expanded toolbar is not "floating" but is anchored to left and right side of screen
-  Remove recent bees
- Add links to Bees, Tools, Knowledge with amount of each
- When in Bees, Tools, or Knowledge, sessions are global (at workspace level under the hood)
- Workspace is removed
- Workspace (if displayed) is shown on top nav, not lefthand toolbar and workspace actions (rename, delete / leave) are shown in overflow menu under workspace switcher. Note: we plan to comment out workspace due to confusion discovered by user studies cc: @spdempsey)

## Example screens (see Figma for actual specs)
![Shell (4)](https://github.com/user-attachments/assets/bdeb6751-7240-4b16-a708-94f69567247a)
![Screenshot 2024-11-12 at 4 40 05 PM](https://github.com/user-attachments/assets/b98b64d6-ca5c-442b-ac7a-a53317b52dd7)

---

To consider for future interation:
- When in a bee, sessions should be bee related

**Comment by abatlaw** [comment]
Note: may be minimal design changes added to this ticket based on Artifact Builder experience epic
