### ISSUE TITLE
Components Library

### ISSUE THREAD

**Issue by tonxxd** [i-am-bee/bee-ui#84]
Create a Bee React Components library to easily integrate the chat in third party dashboards and tools

## Description
Quite often within FlowPilot (cc @mmurad2 ) we were asked for the ability to embed the chat in third party applications, referencing the "agent" configured beforehand
I think having this ability will make it much easier to distribute research technology though bee to final users, instead of creating custom UIs each time or iframes

## Proposal
It would be awesome to be able to do something like

```js
import { BeeChat } from "bee-agent-framework/react"

function App(){ 
  return <BeeChat agent="agent_id" allowFilesUpload  />
}

```

e.g. random dashboard with component integrated
<img width="839" alt="Screenshot 2024-11-19 at 13 40 22" src="https://github.com/user-attachments/assets/17336c2a-8452-4d93-8f79-eea1d7c20f4c">

**Comment by mmurad2** [comment]
Hi @tonxxd thanks for the proposal! This has been something we have been thinking about but unfortunately we do not have bandwidth to look into for the next couple of sprints. We're considering some alternatives between creating our own components vs adopted existing ones. I will close for now and re-open once bandwidth permits!

cc: @geneknit
