### ISSUE TITLE
Bee stack - raw prompt is undefined (local, ollama)

### ISSUE THREAD

**Issue by planetf1** [i-am-bee/bee-ui#89]
## Summary

When using the Bee stack locally (podman compose), together with ollama running locally, with the default Bee Assistant, the **raw prompt** is reported as **undefined** 

[ note: see below for sw config ]

## Details 

For example:

<img width="1384" alt="Screenshot 2024-10-30 at 10 33 01" src="https://github.com/user-attachments/assets/a8429262-0189-4514-8ac3-8321edd64778">
<img width="1384" alt="Screenshot 2024-10-30 at 10 33 05" src="https://github.com/user-attachments/assets/927e03de-3df2-4ba2-b79b-59fde451d52f">

Note: If the same operation is done on an internal deployment, the bee assistant is able to report raw prompt 

Both the default assistant, and a new, custom, agent produce the same result.

## Version

git HEAD is at 71101f9e3915b261f442f4f942238533772f4e37, with the two additional commits from https://github.com/i-am-bee/bee-stack/pull/10 applied. Further the bee-api is at e7ced3f1ce87e8cd621d218531ef8ee961149d39 (compose yml updated to use a locally build container with this) since this was needed to allow use  local llama

## Additional Info

It's possible that the issue relates to use of ollama locally.
not noticed anything obvious in container logs - anything particular to check?

**Comment by Tomas2D** [comment]
The raw Prompt button should not show if there is no raw prompt available. This seems to be a bug.

**Comment by kapetr** [comment]
Fixed by 036c856
